language: node_js
node_js:
  - "4"  # Maintenance
  - "6"  # Active LTS
  - "8"  # Current Active LTS
  - "9"  # Current
matrix:
  allow_failures:
    - node_js: "9"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_script:
  - cp .env.example .env
branches:
  only:
    - master
    - develop
    - patch
script:
  - yarn test:coverage
after_script:
  - yarn report-coverage
addons:
  apt:
    sources:
      - mongodb-upstart
      - sourceline: 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
    packages:
      - mongodb-org-server
      - mongodb-org-shell
