language: node_js
node_js:
  - "4.8"
  - "6.10"
  - "7.6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_script:
  - cp .env.example .env
branches:
  only:
    - master
    - develop
    - patch
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
